spring:
  application:
    name: springflix-movies
  cache:
    type: redis
  data:
    redis:
      # Workaround for https://github.com/spring-cloud/spring-cloud-bindings/issues/87:
      host: ${spring.redis.host}
      password: ${spring.redis.password}

app:
  client:
    connectTimeout: 30s
    readTimeout: 30s
  cache:
    ttl: 10m
  tmdb:
    api:
      url: https://api.themoviedb.org
      key:

server:
  port: ${PORT:8081}

springdoc:
  api-docs:
    path: /api/openapi

management:
  endpoints:
    web:
      exposure:
        include: "*"
  otlp:
    metrics:
      export:
        enabled: false

---

spring:
  config:
    activate:
      on-cloud-platform: kubernetes

management:
  otlp:
    metrics:
      export:
        enabled: true
