spring:
  application:
    name: springflix-movies
  cache:
    type: redis

app:
  client:
    connectTimeout: 30s
    readTimeout: 30s
  cache:
    ttl: 10m
  tmdb:
    api:
      url: https://api.themoviedb.org
      key:

server:
  port: ${PORT:8081}

management:
  endpoints:
    web:
      exposure:
        include: "*"
